### ISSUE TITLE
Regions in Chicago and Boston wrong

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#61]
Chicago: Economic region is still showing up as the MSA. The Economic region should not Include Porter, Jasper, Newton, Grundy, Kendall, DeKalb Counties but currently does.
Boston: MSA is still showing up incorrectly. The MSA should not include Worcester & Bristol Counties but currently does.

**Comment by dana-rg** [comment]
@wklumpen I checked the Boston MSA and Chicago ER data in the drive and they look correct. They were updated in Mar/Apr, so I think this just needs a fresh upload.

**Comment by wklumpen** [comment]
Chicago is fixed. Next up is Boston.

**Comment by dana-rg** [comment]
Boston msa is fixed and uploaded.

**Comment by wklumpen** [comment]
Changes should now be reflected in the maps. Please re-open if they are still incorrect.
